version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout
      - run: echo "hello world"
      - run: ssh -o "StrictHostKeyChecking no" backup.drazisil.com ls
