version: 2

jobs:
    build:
        docker:
            - image: buildpack-deps:artful

        steps:
            - checkout

            - setup_remote_docker
            
            - run:
                name: Install Docker
                command: |
                  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
                  apt update
                  apt install docker-ce

            - run:
                name: Test Docker
                command: docker run ubuntu uname -a

            - run:
                name: Test Docker The Right Way (tm)
                command: docker ps
