version: 2

jobs:
    build:
        docker:
            - image: buildpack-deps:artful

        steps:
            - checkout

            - setup_remote_docker

            - run:
                name: Test Docker
                command: docker run ubuntu uname -a

            - run:
                name: Build image
                command: docker ps
