version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: |
          COMMIT_SHA=$(git rev-parse --short HEAD) \
          echo 1: ${COMMIT_SHA}
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo 2: ${COMMIT_SHA}
          echo 3: $COMMIT_SHA

