version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
        environment:
          CTM_BASE_URL: http://127.0.0.1:9000

      - image: drazisil/private-test:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
