version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: |
          COMMIT_SHA=$(git rev-parse --short HEAD) \
          echo ${COMMIT_SHA}
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo ${COMMIT_SHA}
          echo $COMMIT_SHA

